In [1]:
import pandas as pd
import numpy as np

# Q1. Pandas version

In [2]:
pd.__version__

'2.2.2'

In [22]:
df = pd.read_csv('../data/laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Q2. Records count

In [23]:
len(df)

2160

# Q3. Laptop brands

In [24]:
# How many laptop brands are presented in the dataset?
df['Brand'].nunique()

27

# Q4. Missing values

In [25]:
# How many columns in the dataset have missing values?
(df.isnull().sum() > 0).sum()

np.int64(3)

# Q5. Maximum final price

In [26]:
# What's the maximum final price of Dell notebooks in the dataset?
df.query('Brand == "Dell"')['Final Price'].max()

np.float64(3936.0)

# Q6. Median value of Screen

In [27]:
# Find the median value of Screen column in the dataset.
df['Screen'].median()

np.float64(15.6)

In [28]:
# Next, calculate the most frequent value of the same Screen column.
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [29]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df['Screen'] = df['Screen'].fillna(df['Screen'].mode()[0])

# Now, calculate the median value of Screen once again.
df['Screen'].median()

np.float64(15.6)

# Q7. Sum of weights

In [55]:
# Select all the "Innjoo" laptops from the dataset.
# Select only columns RAM, Storage, Screen.
df.query('Brand == "Innjoo"')[['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [56]:
# df.query('Brand == "Innjoo"')[['RAM', 'Storage', 'Screen']].values

In [57]:
# Get the underlying NumPy array. Let's call it X.
X = df.query('Brand == "Innjoo"')[['RAM', 'Storage', 'Screen']].to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [58]:
X.T.dot(X)

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [59]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [60]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = [1100, 1300, 800, 900, 1000, 1100]

In [65]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
XTX_inv = np.linalg.inv(XTX)
w = (XTX_inv @ X.T) @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [66]:
# What's the sum of all the elements of the result?
w.sum()

np.float64(91.29988062995818)